import type { Hardware } from '@/interfaces/hardware'

export const data: Array<Hardware> = [
  {
    id: 1,
    cover: '/images/hardware/Hardware-1.jpg',
    title: 'Server Toska Intel Xeon',
    rating: 5,
    ratingCount: 20,
    price: '7.500.000',
    category: 'Beginner',
  },
  {
    id: 2,
    cover: '/images/hardware/Hardware-7.jpg',
    title: 'Toska One Side Cashier',
    rating: 5,
    ratingCount: 15,
    price: '4.000.000',
    category: 'Intermediate',
  },
  {
    id: 3,
    cover: '/images/hardware/Hardware-2.jpg',
    title: 'Toska Double Side Cashier',
    rating: 4,
    ratingCount: 9,
    price: '4.900.000',
    category: 'Beginner',
  },
  {
    id: 4,
    cover: '/images/hardware/Hardware-3.jpg',
    title: 'Toska Barcode Scanner',
    rating: 5,
    ratingCount: 14,
    price: '500.000',
    category: 'Intermediate',
  },
  {
    id: 5,
    cover: '/images/hardware/Hardware-4.jpg',
    title: 'Toska CashDrawer',
    rating: 4,
    ratingCount: 32,
    price: '450.000',
    category: 'Intermediate',
  },
  {
    id: 6,
    cover: '/images/hardware/Hardware-5.jpg',
    title: 'Receipt Printer Epson TM-220',
    rating: 5,
    ratingCount: 28,
    price: '2.450.000',
    category: 'Beginner',
  },
  {
    id: 7,
    cover: '/images/hardware/Hardware-6.jpg',
    title: 'Xprinter XP-MD0 Printer Label Barcode Sticker',
    rating: 5,
    ratingCount: 6,
    price: '1.250.000',
    category: 'Beginner',
  },
]
