export const pricingData = [
  {
    levelName: 'Starter',
    subtitle: 'Untuk usaha kecil yang membutuhkan kemudahan operasional lengkap',
    price: '1.499K',
    features: [
      'WEB Base | Cross Platform 1',
      '2 in 1 POS ( Barang & Jasa) ',
      'Dashboard Root',
      'Dashboard Kasir',
      'Dashboard Admin Toko',
      'Laporan Pembelian Lengkap ',
      'Laporan Penjualan Lengkap ',
      'Pengaturan Lengkap',
      'Pencatatan Omset Bulanan',
      'Management Hutang I Piutang I Retur',
      'management Distributor I Reseller',
      'Laporan Bulanan',
      'Device Printing',
    ],
  },
  {
    levelName: 'Advance',
    subtitle: 'Untuk usaha berkembang yang membutuhkan fitur lengkap',
    price: '2.399K',
    features: [
      'WEB Base | Cross Platform 1',
      '2 in 1 POS ( Barang & Jasa) ',
      'Dashboard Root',
      'Dashboard Kasir',
      'Dashboard Admin Toko',
      'Dashboard Owner',
      'Laporan Pembelian Lengkap ',
      'Laporan Penjualan Lengkap ',
      'Pengaturan Lengkap',
      'Pencatatan Omset Bulanan',
      'Pencatatan Profit Bulanan',
      'Management Hutang I Piutang I Retur',
      'management Distributor I Reseller',
      'Laporan Bulanan',
      'Management Etalase',
      'Grafik Analisa Bulanan',
      'Device Printing',
    ],
  },
  {
    levelName: 'Professional',
    subtitle: 'Untuk usaha maju yang membutuhkan fitur otomasi dan kelengkapan laporan',
    price: '2.899K',
    features: [
      'WEB Base | Cross Platform 1',
      '2 in 1 POS ( Barang & Jasa) ',
      'Dashboard Root',
      'Dashboard Kasir',
      'Dashboard Admin Toko',
      'Dashboard Owner',
      'Laporan Pembelian Lengkap ',
      'Laporan Penjualan Lengkap ',
      'Pengaturan Lengkap',
      'Management Keuangan',
      'Pencatatan Omset Bulanan | Tahunan',
      'Pencatatan Profit Bulanan | Tahunan',
      'Management Hutang I Piutang I Retur',
      'management Distributor I Reseller',
      'Laporan Bulanan | Tahunan',
      'Management Etalase',
      'Management Target Penjualan',
      'Full Grafik Analisa Bulanan | Tahunan',
      'Device Printing',
      'Central Printing',
    ],
  },
]
